### ISSUE TITLE
ES6 compatibility

### ISSUE THREAD

**Issue by jgb** [pmourlanne/fiqs#2]
Hello Pierre :wave:,

I was testing fiqs with ES6, and I ran into 5 tests that are broken:

- fiqs/tests/test_fields.py::test_mapping_from_model FAILED
- fiqs/tests/test_fields.py::test_mapping_from_model_child_class FAILED
- fiqs/tests/test_query.py::test_order_by FAILED
- fiqs/tests/test_query.py::test_order_by_multiple_group_by FAILED
- fiqs/tests/test_query.py::test_order_by_field_with_choices FAILED

The first two end with an exception that I also get when I try to run our own code, which goes like this:

`AttributeError: 'Nested' object has no attribute 'field'`

The exception happens in: 

`fiqs/models.py:94: in get_mapping
    nested_mapping.field(field.storage_field, field.type)`

I suppose this is due to a breaking change in elasticsearch_dsl >= 6:

https://elasticsearch-dsl.readthedocs.io/en/latest/Changelog.html#id11

I tried playing around with the fiqs code, using Nested(InnerDoc) as the changelog of elasticsearch_dsl seems to say, but I can't figure it out :crying_cat_face:.

I'll do some reading and try again, but any help is very welcome :beer:.

Jan

**Comment by pmourlanne** [comment]
Here's how I see us going forward and have fiqs work on ES 6:
- Upgrade `elasticsearch` and `elasticsearch-dsl` requirements
- Re-generate search outputs using an ES 6 docker container (see `test_elasticsearch.py`)
- Fix the tests one by one
- Make a new release, compatible with ES 6

**Comment by pmourlanne** [comment]
By the way, I expect that re-generating the search outputs will make a lot of other tests fail :santa:
